#!/bin/bash

set -e

export GOROOT=/usr/share/go
export GOPATH=/go
export PATH=/usr/share/go/bin:$GOPATH/bin:$PATH

echo "--- setting up build environment"
mkdir -p /go/src/github.com/exchangegroup/bruce
rsync -r --exclude .git /source/ /go/src/github.com/exchangegroup/bruce/

cd /go/src/github.com/exchangegroup/bruce/

echo "--- getting dependencies"
go get -t ./...
go get github.com/kisielk/errcheck

echo "--- testing"
make test

echo "--- building"
go install github.com/exchangegroup/bruce/bin/bruce

echo "--- packaging"
rm $GOPATH/bin/errcheck #don't want to ship errcheck
mkdir /source/output/
cp $GOPATH/bin/* /source/output/
